### ISSUE TITLE
Colored guild/player names in nTooltip

### ISSUE THREAD

**Issue by Ag3ntunkn0wn** [lithammer/NeavUI#153]
Not really an issue, more of a request but would it be possible to make other players names be their class color in the tooltip and also color the guild name kinda like other addons do where your your guild and people in your guild are something like purple and everyone elses is a light blue? (using what tiptac does by default)

I've been using this code to get player names colored for years (got it off mmo champ or something) but would be nice if it did it by default.

```
GameTooltip:HookScript("OnTooltipSetUnit", function(GameTooltip)
    --print("OnTooltipSetUnit")
    local _, unit = GameTooltip:GetUnit()
    --print(unit)
    if UnitIsPlayer(unit) then
        --print("UnitIsPlayer")
        local _, class = UnitClass(unit)
        --print(class)
        local color = class and (CUSTOM_CLASS_COLORS or RAID_CLASS_COLORS)[class]
        if color then
            local text = GameTooltipTextLeft1:GetText()
            --print(text)
            GameTooltipTextLeft1:SetFormattedText("|cff%02x%02x%02x%s|r", color.r * 255, color.g * 255, color.b * 255, text:match("|cff\x\x\x\x\x\x(.+)|r") or text)
        end
    end
end)
```

Thanks.

**Comment by Grimsbain** [comment]
We can easily add a modified version of this code for the player names (it currently only shows friendly people in their class color) but the guild name should already be colored if the person is in the same guild.

**Comment by Grimsbain** [comment]
@renstrom I have the code for this (character names only since the guild name already changes color) done if this is something you think we should do.

**Comment by renstrom** [comment]
Don't we already show the class color on the level/race/class row of the tooltip? Also, I could swear we had a "class coloured border" option before, but can't find it anymore...

**Comment by Grimsbain** [comment]
Currently enemy names are shown in red not their class color and this would color them like we do for ally tooltips. Personally I don't care but I figured I would work on it if people wanted it.

http://imgur.com/WBFHQoi
