### ISSUE TITLE
`showOnMouseover = true` makes the tooltip laggy and "jumpy"

### ISSUE THREAD

**Issue by lithammer** [lithammer/NeavUI#179]
Reported on WoWI. When setting `showOnMouseover = true` in nTooltip it's reported as being laggy and jumps back to the previously hovered NPC.

> [..]when mousing over multiple npc's the tooltip kind of lags and jumps back to the last npc I mouse over before it goes to the one I'm currently mousing over.

**Comment by Grimsbain** [comment]
I did some testing and this behavior still shows up if you apply the GameTooltip_SetDefaultAnchor hooksecurefunc to the default tooltips. So if it can be fixed it is probably be in that function but I have no idea how to do it.

**Comment by Grimsbain** [comment]
I remember testing this and it being a real bug but it doesn't seem to happen anymore.
