### ISSUE TITLE
nMainbar and Join Random Battlegrounds

### ISSUE THREAD

**Issue by Leiludallas** [lithammer/NeavUI#241]
Hi,

When I try to join random battlegrounds queue, I have this message:

> nMainbar has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI.

It occurs only for this queue. It's ok for arena or pve queues.
Queing for random bg works when I disable nMainbar.

**Comment by Grimsbain** [comment]
This isn't actually a problem with any of your addons but with the Blizzard's code. You can see a full rundown of why this happens here.

https://www.townlong-yak.com/bugs/afKy4k-HonorFrameLoadTaint

**Comment by Grimsbain** [comment]
Should be fixed with ae52692eb9366eea9b12afedd439ff5dfbf8bd2c.
