### ISSUE TITLE
Empty boss frame health bar

### ISSUE THREAD

**Issue by Roflstomp209** [lithammer/NeavUI#245]
Found another glitch in oUF_Neav.
The boss frames are not displaying any status information.

![wowscrnshot_072818_123456](https://user-images.githubusercontent.com/41709240/43360102-5656baf8-9264-11e8-81cb-f0f1f43785ed.jpg)

**Comment by Grimsbain** [comment]
Fixed with 382cf6f01e1943f9ad819b0c015403afd9fcc9ec.
