### ISSUE TITLE
Lua error - Portrait timers

### ISSUE THREAD

**Issue by Sjukhus** [lithammer/NeavUI#246]
Hi,

First time poster, love this UI. So the newest build works most of the time, however there's an issue with portrait timers:

Message: Interface\AddOns\oUF_Neav\modules\portraittimers.lua:140: attempt to perform arithmetic on field 'expires' (a string value)
Time: Tue Jul 31 12:23:34 2018
Count: 654
Stack: Interface\AddOns\oUF_Neav\modules\portraittimers.lua:140: attempt to perform arithmetic on field 'expires' (a string value)
Interface\AddOns\oUF_Neav\modules\portraittimers.lua:140: in function <Interface\AddOns\oUF_Neav\modules\portraittimers.lua:131>

Locals: self = oUF_Neav_PetHealthPortraitTimer {
 expires = "pet"
 Remaining = <unnamed> {
 }
 elapsed = 0
 duration = 104284.059
 Icon = <unnamed> {
 }
 0 = <userdata>
}
elapsed = 0.010000000707805
(*temporary) = "pet"
(*temporary) = 104284.1
(*temporary) = 104284.1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'expires' (a string value)"
GetTime = <function> defined =[C]:-1
ExactTime = <function> defined @Interface\AddOns\oUF_Neav\modules\portraittimers.lua:115
FormatTime = <function> defined @Interface\AddOns\oUF_Neav\modules\portraittimers.lua:119

Thanks

**Comment by lithammer** [comment]
Thanks! Should hopefully be fixed by 
https://github.com/lithammer/NeavUI/commit/dd9ddb40deb5fea0487024e620e3f8eada1581d.6

**Comment by Sjukhus** [comment]
That was quick, can confirm that it works with the newest version. Thanks!
