### ISSUE TITLE
Fix "Bottom Right Bar" position

### ISSUE THREAD

**Issue by lithammer** [lithammer/NeavUI#247]
The `MultiBarBottomRight` bar has changed quite a lot in 8.0, i.e. ~~now only contains 6 buttons (instead of 12) and~~ changed place.

![multibarbottomright](https://user-images.githubusercontent.com/177685/43457486-4dd09934-94c7-11e8-84e3-bfedd5c86cf3.png)

**Comment by ckienast** [comment]
That's not correct. It has still 12 Buttons, but in 2 by 6 rows.  See [here](https://static.icy-veins.com/forum-files/uploads/monthly_2018_02/WoWScrnShot_020818_035108.jpg.10b20a7dadf92a4d1b1daaa0326665b4.jpg).

In NeavUI all 12 slots are missing if you activate it, it's just the image behind it.
