### ISSUE TITLE
Can no longer change border color in nMainbar

### ISSUE THREAD

**Issue by Ag3ntunkn0wn** [lithammer/NeavUI#250]
I always darken the border colors in nMainbar by changing:

`Normal = { 1, 1, 1, 1 },`

to something like

`Normal = { .4, .4, .4, 1 },`

But this no longer works in the new nMainbar, instead it only changes the border color of the "FakeBottomRightBar" bar but if I go into the settings and enable "Always Show ActionBars" then every bar takes the color besides the main bottom bar but it's only temporary as a reload or dragging any ability out of the bar to another reverts the border colors back to default.

The stance bar also isn't skinned anymore.

**Comment by Grimsbain** [comment]
Should be fixed with 1e4755b6ab5692e43ff7ca5915da4761d36f3f75 and ec50178be751b78fdbe3388629e603ae193d9b99.
