### ISSUE TITLE
Error while toggling the raid frame anchor via the pico menu

### ISSUE THREAD

**Issue by lithammer** [lithammer/NeavUI#251]
Trying to toggle the raid frame mover via the pico menu produces this error:

```
Message: Interface\AddOns\nMainbar\modules\picomenu.lua:252: attempt to call field 'oUF_Neav_Raid' (a nil value)
Time: Mon Aug  6 10:30:49 2018
Count: 1
Stack: Interface\AddOns\nMainbar\modules\picomenu.lua:252: attempt to call field 'oUF_Neav_Raid' (a nil value)
Interface\AddOns\nMainbar\modules\picomenu.lua:252: in function `func'
Interface\FrameXML\UIDropDownMenu.lua:935: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: (*temporary) = nil
(*temporary) = "toggle"
(*temporary) = "attempt to call field 'oUF_Neav_Raid' (a nil value)"
```

**Comment by Grimsbain** [comment]
Yeah my version has a different slash command. At this point not including any addons that are unique to my version the only addons with any major differences are nCore, nMinimap, oUF_Neav and oUF_NeavRaid. I do have some slight changes to Colorz in my version but it they are tied to changes in oUF_Neav.

**Comment by lithammer** [comment]
We should probably start porting the changes to nCore, nMinimap, oUF_Neav and oUF_NeavRaid as well. I had a look and I didn't really see anything out of the ordinary.
