### ISSUE TITLE
ncore not working, errors

### ISSUE THREAD

**Issue by boingylol** [lithammer/NeavUI#254]
Message: Interface\AddOns\nCore\modules\altbuy.lua:4: attempt to index global 'nCoreDB' (a nil value)
Time: Wed Aug  8 17:04:54 2018
Count: 1
Stack: Interface\AddOns\nCore\modules\altbuy.lua:4: attempt to index global 'nCoreDB' (a nil value)
Interface\AddOns\nCore\modules\altbuy.lua:4: in function `AltBuy'
Interface\AddOns\nCore\core.lua:23: in function <Interface\AddOns\nCore\core.lua:16>

Locals: self = <table> {
 Durability = <function> defined @Interface\AddOns\nCore\modules\durability.lua:3
 CreateCheckBox = <function> defined @Interface\AddOns\nCore\options.lua:48
 AltBuy = <function> defined @Interface\AddOns\nCore\modules\altbuy.lua:3
 CreateAnchor = <function> defined @Interface\AddOns\nCore\modules\library.lua:5
 IsTaintable = <function> defined @Interface\AddOns\nCore\modules\library.lua:35
 Dressroom = <function> defined @Interface\AddOns\nCore\modules\dressroom.lua:3
 Skins = <function> defined @Interface\AddOns\nCore\modules\skins.lua:3
 SetDefaultOptions = <function> defined @Interface\AddOns\nCore\options.lua:19
 AutoQuest = <function> defined @Interface\AddOns\nCore\modules\autoquest.lua:3
 VignetteAlert = <function> defined @Interface\AddOns\nCore\modules\vignette.lua:5
 L = <table> {
 }
 QuestTracker = <function> defined @Interface\AddOns\nCore\modules\questtracker.lua:3
 MapCoords = <function> defined @Interface\AddOns\nCore\modules\coords.lua:3
 MoveTalkingHeads = <function> defined @Interface\AddOns\nCore\modules\movetalkinghead.lua:3
 Fonts = <function> defined @Interface\AddOns\nCore\modules\fonts.lua:3
 RegisterDefaultSetting = <function> defined @Interface\AddOns\nCore\options.lua:8
 ObjectiveTracker = <function> defined @Interface\AddOns\nCore\modules\objectivetracker.lua:4
 AutoGreed = <function> defined @Interface\AddOns\nCore\modules\autogreed.lua:3
 LockInCombat = <function> defined @Interface\AddOns\nCore\options.lua:38
 ArchaeologyHelper = <function> defined @Interface\AddOns\nCore\modules\archaeology.lua:3
 ErrorFilter = <function> defined @Interface\AddOns\nCore\modules\errors.lua:3
 SpellID = <function> defined @Interface\AddOns\nCore\modules\spellid.lua:3
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'nCoreDB' (a nil value)"
nCore = <table> {
 Durability = <function> defined @Interface\AddOns\nCore\modules\durability.lua:3
 CreateCheckBox = <function> defined @Interface\AddOns\nCore\options.lua:48
 AltBuy = <function> defined @Interface\AddOns\nCore\modules\altbuy.lua:3
 CreateAnchor = <function> defined @Interface\AddOns\nCore\modules\library.lua:5
 IsTaintable = <function> defined @Interface\AddOns\nCore\modules\library.lua:35
 Dressroom = <function> defined @Interface\AddOns\nCore\modules\dressroom.lua:3
 Skins = <function> defined @Interface\AddOns\nCore\modules\skins.lua:3
 SetDefaultOptions = <function> defined @Interface\AddOns\nCore\options.lua:19
 AutoQuest = <function> defined @Interface\AddOns\nCore\modules\autoquest.lua:3
 VignetteAlert = <function> defined @Interface\AddOns\nCore\modules\vignette.lua:5
 L = <table> {
 }
 QuestTracker = <function> defined @Interface\AddOns\nCore\modules\questtracker.lua:3
 MapCoords = <function> defined @Interface\AddOns\nCore\modules\coords.lua:3
 MoveTalkingHeads = <function> defined @Interface\AddOns\nCore\modules\movetalkinghead.lua:3
 Fonts = <function> defined @Interface\AddOns\nCore\modules\fonts.lua:3
 RegisterDefaultSetting = <function> defined @Interface\AddOns\nCore\options.lua:8
 ObjectiveTracker = <function> defined @Interface\AddOns\nCore\modules\objectivetracker.lua:4
 AutoGreed = <function> defined @Interface\AddOns\nCore\modules\autogreed.lua:3
 LockInCombat = <function> defined @Interface\AddOns\nCore\options.lua:38
 ArchaeologyHelper = <function> defined @Interface\AddOns\nCore\modules\archaeology.lua:3
 ErrorFilter = <function> defined @Interf

**Comment by Grimsbain** [comment]
Thanks for the report. Fixed with 26f960f175f6459aabdbc0f42705a903a9b8cc17.
