### ISSUE TITLE
nTooltip hideRealmText Option

### ISSUE THREAD

**Issue by Grimsbain** [lithammer/NeavUI#255]
What exactly does the hideRealmText option in nTooltip do? I searched Blizzards code and the only string that is still in use is FOREIGN_SERVER_LABEL aka (*). I wanted to make sure this is actually useless now since I don't play on a connected server.

**Comment by lithammer** [comment]
I think it's supposed to replace the realm/server name on the tooltip with `(*)`. However it' seems like it's not working very well... It shows regardless if you set it to `true` or `false`.

<img width="154" alt="screen shot 2018-08-08 at 18 48 53" src="https://user-images.githubusercontent.com/177685/43852058-92011ee6-9b3c-11e8-9469-04193e8b177c.png">

**Comment by Grimsbain** [comment]
Isn't that what abbrevRealmNames does?

**Comment by Grimsbain** [comment]
Yeah it should be fine. As far as I can tell this must have been from the early days of connected realms. Removed with 0f21d97ed63e23182a33dc7b8f343db6c410e2ba.
