### ISSUE TITLE
Upload new release to WoWI

### ISSUE THREAD

**Issue by lithammer** [lithammer/NeavUI#256]
@Grimsbain besides #240, do you have any more changes lined up? I'm thinking if it's about time to cut a new release to WoWI since many of the issues raised there have been fixed by now.

**Comment by Grimsbain** [comment]
The only other issue I'm looking into is the mouse over action bar not always auto hiding after you exit a vehicle or after a pet battle.

**Comment by Grimsbain** [comment]
Found a solution to the mouse over bug. I just hooked into the function that handles slide out of the right action bars. Tested when exiting a vehicle and exiting a pet battle and it worked without any problems.

**Comment by lithammer** [comment]
Excellent!

**Comment by Grimsbain** [comment]
It seems the scaling the MainMenuBar isn't working but I'm running into the same issues I had trying to move the bottom right action buttons. Blizzard has a bunch of new functions that deal with managing MainMenuBar and they don't like people messing with them.

**Comment by lithammer** [comment]
It would be a shame if we had to write the actionbars from scratch just to get scaling etc working again.

**Comment by Grimsbain** [comment]
I have been working on the MainMenuBar scaling issue but at this point I have no idea when that could be finished if ever. So it probably isn't worth holding up a new release over. Unless we get some bug reports or small feature requests we are probably good to go.

**Comment by lithammer** [comment]
Tagged and uploaded 8.0.1.

https://github.com/lithammer/NeavUI/releases/tag/8.0.1
