### ISSUE TITLE
ouf_neavraid lose some option after no lua config

### ISSUE THREAD

**Issue by boingylol** [lithammer/NeavUI#257]
cant set  "aggro" text, space between frames, only mana as power bar, sad gui config =(  
lua config have this and much more

**Comment by boingylol** [comment]
and hidden role too

**Comment by Grimsbain** [comment]
I will work on getting the space between frames, only mana as power bar, and hidden role into the gui but I don't think the aggro text is really needed.

**Comment by Grimsbain** [comment]
Added the above with 80ada30acfc4d7c976ccc59598110fc60acbbd00.
