### ISSUE TITLE
Female character for battlenet friends causes Lua error

### ISSUE THREAD

**Issue by hwiegard** [lithammer/NeavUI#258]
If a battlenet friend is logged in with a female character an lua error in tab.xml line 400 shows up because classc is nil. To fix this the attached patch can be used [tab.txt](https://github.com/lithammer/NeavUI/files/2275905/tab.txt).

**Comment by Grimsbain** [comment]
Thanks for the heads up. For future reference what language client do you use? The english versions of tables are identical for both genders so it was never a problem for me. Fixed in f1b2c909f03792341d93a7b847c8756ff5893e5d.

**Comment by hwiegard** [comment]
Using a german client several class names are different, e.g. `Krieger` (male) and `Kriegerin` (female) for `Warrior`.
