### ISSUE TITLE
oUF_Neav - Show party false

### ISSUE THREAD

**Issue by Technojo01** [lithammer/NeavUI#259]
Hey guys,

Maybe I'm missing something, but when setting show party = false, I'm still seeing them in dungeons (5 man).  Thanks.

`        ["party"] = {
            scale = 1.193,
            show = false,
            hideInRaid = true,`

**Comment by boingylol** [comment]
try to update ouf and ouf_neav. me fine hided.

**Comment by Grimsbain** [comment]
Yeah I don't see how this could be a problem. oUF handles hiding the party frames and the oUF_Neav party frames don't even spawn if that isn't set to true. If you continue to have problems can you get a screenshot of the problem.

**Comment by Technojo01** [comment]
OIK, maybe I've got your old modified oUF version then. Let me try it.

**Comment by Technojo01** [comment]
Well, still happening using only oUF (latest) and oUF_Neav addons. Hmm..
![wowscrnshot_081018_152304](https://user-images.githubusercontent.com/17357753/43977455-3db09f20-9cb2-11e8-8aab-9dba37fb1333.jpg)

**Comment by Technojo01** [comment]
I'm not using oUF_Neavraid though! I'm using Vudho instead... when using neav raid, only this shows.

**Comment by Grimsbain** [comment]
Those are the default party frames. Not sure why they would be showing. Here is what the oUF_Neav party frames look like.

![wowscrnshot_081018_102027](https://user-images.githubusercontent.com/140057/43977646-fc16c22a-9ca1-11e8-9d61-b1570ba4b685.jpg)

**Comment by Technojo01** [comment]
OK' using Raid-style party frame hides them!

**Comment by Grimsbain** [comment]
It was probably oUF and VuhDo conflicting. Glad you got it worked out.
