### ISSUE TITLE
nMainbar - Latest changes

### ISSUE THREAD

**Issue by Technojo01** [lithammer/NeavUI#260]
Hey, just updated your latest changes and getting this error upon login:

> Message: ...terface\AddOns\nMainbar\modules\actionbuttonskin.lua:321: Usage: IsUsableAction(slot)
Time: Fri Aug 10 09:00:20 2018
Count: 1250
Stack: ...terface\AddOns\nMainbar\modules\actionbuttonskin.lua:321: Usage: IsUsableAction(slot)
[C]: in function `IsUsableAction'
...terface\AddOns\nMainbar\modules\actionbuttonskin.lua:321: in function <...terface\AddOns\nMainbar\modules\actionbuttonskin.lua:319>
[C]: in function `ActionButton_UpdateRangeIndicator'
Interface\FrameXML\PetActionBarFrame.lua:143: in function <Interface\FrameXML\PetActionBarFrame.lua:111>
Locals: (*temporary) = nil

**Comment by Technojo01** [comment]
OK, happens only if I have my pet out (hunter).

**Comment by Grimsbain** [comment]
Fixed with 4103694a25c13149db1397ba4eda8e540d64d1cf. Thanks for the report.
