### ISSUE TITLE
nMainbar - Equipped Item Border

### ISSUE THREAD

**Issue by twin2** [lithammer/NeavUI#261]
Hi!

This is very minor and might be wrong to label as an issue? im not to familiar with github.. please let me know if i should approach these kind of requests any other way.

Its regarding the equipped state of the border.

Here is a screenshot because im terrible at explaining. 

![image](https://user-images.githubusercontent.com/328699/43990828-5960030a-9d61-11e8-8eb7-6a10fc763ee4.png)

The top border is the desired look im after.. i used to be able to edit this myself in the older versions.. it used to look like this in a very old version i think :)

Now when i try i get the result below. (i set the color to white in the config for testing). It only shows the bordercolor i set in the config on actionbarslot that has a key bound to them,it also ignores the texture i set.

The texture shows if i reload UI but hovering the icon removes coloring and the texture.

I hope this makes sense. let me know if i can provide any information.

I do understand this is low priority and not considered an issue at all.. thank you so much for the great work you put into this UI.

Best regards

/Nin

**Comment by Grimsbain** [comment]
Good news thanks to your request I was able to get this change in and I was able to find some unreported bugs. The build includes a new texture so make sure to do a full game restart to get it to work.
