### ISSUE TITLE
WoWI Description

### ISSUE THREAD

**Issue by Grimsbain** [lithammer/NeavUI#262]
We need to update the description on wowinterface. The "How can I move the player, target and focus frame?" and "Commands" section are out of date. Here is a quick run down of the current slash commands and what has been removed.

oUF_NeavRaid
 * /neavrt - Still the same.
 * Removed /wm, /worldmarkers, /rm, /raidmarkers, /rolecheck, and /rcheck. oUF_NeavRaid now has a custom raid manager. It can be used to place world markers and do other common raid tasks.

oUF_Neav
 * /neav - Toggles the anchors for the player, target, focus, boss, and arena frames.
 * /neavcast - Toggles the anchors for the castbars.
 * Removed /neavreset you can remove any changes you make in the ingame gui.

nCore
 * /alertframemover - Toggles the anchor for the talking head frame.

nMainbar
 * /neavbag - Still the same.
 * /moveextraactionbar - Toggles the anchor for the extra action button.

nTooltip
 * /ntooltip - Toggles the anchor for the tooltip anchor.

**Comment by lithammer** [comment]
Unfortunately I don't own the addon on WoWI, so I can't add co-authors. Will try to ask some admin if they can promote me or something since @Neav has been absent for a long time.

**Comment by Grimsbain** [comment]
It was replaced by the slash command. Hopefully they can transfer it over to you since you are listed on the website.

**Comment by lithammer** [comment]
I've sent them an e-mail now. I suppose plan B is to just create a new addon and deprecate the current one with a huge a banner and links to the new one.

**Comment by lithammer** [comment]
They've added you as a team member now (I'm still not a team leader though).
