### ISSUE TITLE
nMainbar equipped item

### ISSUE THREAD

**Issue by Technojo01** [lithammer/NeavUI#263]
Hello, seems like something not quite right with the latest changes. See pictures below:

![image](https://user-images.githubusercontent.com/17357753/44002674-8fb0f3fc-9e14-11e8-943e-7f1fb714865c.png)

![image](https://user-images.githubusercontent.com/17357753/44002677-98decd28-9e14-11e8-8996-a5b5ac8369e1.png)

**Comment by Grimsbain** [comment]
Did you do a full game restart? We added a new texture so you can't just reload.

**Comment by Technojo01** [comment]
Oh, that was it, sorry :-\
