### ISSUE TITLE
Update Holy power bars

### ISSUE THREAD

**Issue by Nutrition1** [lithammer/NeavUI#269]
Hi,

As I get older my eyes find it increasingly hard to see the holy power number on npower is there any chance you can update the paladin one to remove the mana bar and replace the numbers with something similar to the DK one? https://cdn-wow.mmoui.com/preview/pvw31362.jpg Just like the DK would be perfect! 

Much appreciated

**Comment by Grimsbain** [comment]
Added in 7123043829052e24b15f2017caa761fa317cb5df. I added what you requested and also cleaned most of the code. I have it turned off by default but you can turn it on by setting showRunes under holyPower to true. Also the font size is set to 15 by default and that may be small if you have problems with your eyes but I tested it all the up to 35 and everything looked fine.
