### ISSUE TITLE
Art Bar

### ISSUE THREAD

**Issue by Nutrition1** [lithammer/NeavUI#270]
I promise my last one 

Any chance you could add the following to cvar to hide

MainMenuBarArtFrameBackground
ActionBarDownButton
ActionBarUpButton
Unsure about the frame name for the 1 ( Circled it on the Picture )
Rep bar again unsure of the frame name?

Thanks for help recently been using the addon since it was released on wowinterface 

![addon](https://user-images.githubusercontent.com/42187295/49458255-5ece9080-f7e4-11e8-9e32-a50444cdd1f6.png)

**Comment by lithammer** [comment]
I gotta admit I'm a bit reluctant to add an option that basically removes everything that makes nMainbar what it is 🤔

**Comment by Nutrition1** [comment]
> I gotta admit I'm a bit reluctant to add an option that basically removes everything that makes nMainbar what it is 🤔

I usually use dominoes with the old button facade neav and disable nMainbar, Trying to fade all the addons I use and convert to all Neavui for my UI now. Doesn't matter if not:)
