### ISSUE TITLE
nMinimap Error

### ISSUE THREAD

**Issue by Nutrition1** [lithammer/NeavUI#271]
Most of the evening this pops up while raiding

Message: Interface\AddOns\nMinimap\tab.lua:465: attempt to index local 'classc' (a nil value)
Time: Wed Dec 12 19:26:41 2018
Count: 1
Stack: Interface\AddOns\nMinimap\tab.lua:465: attempt to index local 'classc' (a nil value)
Interface\AddOns\nMinimap\tab.lua:465: in function `nMinimap_UpdateFriendButton'
Interface\AddOns\nMinimap\tab.lua:497: in function `nMinimap_UpdateFriends'
Interface\AddOns\nMinimap\tab.lua:547: in function `nMinimapTab_Friends_UpdateScrollFrame'
Interface\AddOns\nMinimap\tab.lua:583: in function <Interface\AddOns\nMinimap\tab.lua:577>

Locals: entry = FriendsScrollFrameEntry12 {
 RightText = FriendsScrollFrameEntry12RightText {
 }
 LeftText = FriendsScrollFrameEntry12LeftText {
 }
 index = 12
 buttonType = 3
 id = 1
 0 = <userdata>
}
scrollFrame = FriendsScrollFrame {
 offset = 0
 scrollChild = FriendsScrollChild {
 }
 entries = <table> {
 }
 entryHeight = 17
 numEntries = 12
 scrollBar = FriendsScrollFrameScrollBar {
 }
 0 = <userdata>
 totalEntriesHeight = 204
 ScrollBar = FriendsScrollFrameScrollBar {
 }
}
index = 12
height = 17
minWidth = 300.000061
zonec = <table> {
 a = 1
 GetRGB = <function> defined @Interface\SharedXML\Util.lua:663
 OnLoad = <function> defined @Interface\SharedXML\Util.lua:652
 b = 0.750000
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Util.lua:694
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Util.lua:698
 GenerateHexColor = <function> defined @Interface\SharedXML\Util.lua:690
 GetRGBA = <function> defined @Interface\SharedXML\Util.lua:671
 IsEqualTo = <function> defined @Interface\SharedXML\Util.lua:656
 g = 0.750000
 r = 0.750000
 SetRGBA = <function> defined @Interface\SharedXML\Util.lua:679
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Util.lua:667
 SetRGB = <function> defined @Interface\SharedXML\Util.lua:686
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Util.lua:675
}
classc = nil
levelc = <table> {
 b = 0
 font = "QuestDifficulty_Difficult"
 g = 0.820000
 r = 1
}
info = <table> {
 connected = true
 guid = "Player-1588-09C49433"
 afk = false
 referAFriend = false
 name = "Ziraz"
 className = "Paladin"
 dnd = false
 level = "120"
 area = "Boralus Harbor"
}
chatFlag = ""
(*temporary) = <function> defined @Interface\SharedXML\Util.lua:616
(*temporary) = "Ziraz"
(*temporary) = "ffffd100"
(*temporary) = nil
(*temporary) = "|c%s%s"
(*temporary) = "ffffd100"
(*temporary) = "120"
(*temporary) = "120"
(*temporary) = 0
(*temporary) = "ffffd100"
(*temporary) = 0
(*temporary) = 0.820000
(*temporary) = 0
(*temporary) = 1
(*temporary) = <function> defined @Interface\SharedXML\Util.lua:679
(*temporary) = <table> {
 a = 1
 GetRGB = <function> defined @Interface\SharedXML\Util.lua:663
 OnLoad = <function> defined @Interface\SharedXML\Util.lua:652
 b = 0
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Util.lua:694
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Util.lua:698
 GenerateHexColor = <function> defined @Interface\SharedXML\Util.lua:690
 GetRGBA = <function> defined @Interface\SharedXML\Util.lua:671
 IsEqualTo = <function> defined @Interface\SharedXML\Util.lua:656
 g = 0.820000
 r = 1
 SetRGBA = <function> defined @Interface\SharedXML\Util.lua:679
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Util.lua:667
 SetRGB = <function> defined @Interface\SharedXML\Util.lua:686
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Util.lua:675
}
(*temporary) = 1
(*temporary) = 0.820000
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @Interface\SharedXML\Util.lua:675
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'classc' (a nil value)"
FriendListEntries = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }

**Comment by Grimsbain** [comment]
Woops forgot to update the className variable to use the new table format. Should be fine now.
