### ISSUE TITLE
ouf_neav raid error

### ISSUE THREAD

**Issue by boingylol** [lithammer/NeavUI#272]
Message: ...avRaid\modules\oUF_Freebgrid\oUF_Freebgrid_Auras.lua:231: attempt to index field 'auras' (a nil value)
Time: Sat Dec 15 16:27:15 2018
Count: 81
Stack: ...avRaid\modules\oUF_Freebgrid\oUF_Freebgrid_Auras.lua:231: attempt to index field 'auras' (a nil value)
...avRaid\modules\oUF_Freebgrid\oUF_Freebgrid_Auras.lua:231: in function <...avRaid\modules\oUF_Freebgrid\oUF_Freebgrid_Auras.lua:224>
...avRaid\modules\oUF_Freebgrid\oUF_Freebgrid_Auras.lua:356: in function `func'
Interface\AddOns\oUF\events.lua:50: in function <Interface\AddOns\oUF\events.lua:48>
(tail call): ?

Locals: icons = oUF_Raid1UnitButton1FreebAuras {
 0 = <userdata>
 button = <unnamed> {
 }
}
_ = "player"
icon = <unnamed> {
 0 = <userdata>
 buff = false
 parent = oUF_Raid1UnitButton1FreebAuras {
 }
 remaining = <unnamed> {
 }
 count = <unnamed> {
 }
 overlay = <unnamed> {
 }
 priority = 0
 icon = <unnamed> {
 }
 asc = false
}
name = "Резонирующий щит"
_ = 1769069
_ = 0
dtype = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'auras' (a nil value)"
ns = <table> {
 CreateSharedMeidaDropdown = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:496
 CreateDropdown = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:401
 dispelPriority = <table> {
 }
 CreateCheckBox = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:243
 CreateSlider = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:308
 CreateLabel = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:214
 GetDefaultValue = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:164
 RegisterControl = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:154
 CreateAnchor = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:95
 MultiCheck = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:23
 pairsByKeys = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:79
 LockInCombat = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:144
 FormatTime = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:11
 L = <table> {
 }
 utf8sub = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:56
 RegisterDefaultSetting = <function> defined @Interface\AddOns\oUF_NeavRaid\functions.lua:33
}
instDebuffs = <table> {
}
dispellist = <table> {
 Poison = true
 Magic = false
 Disease = true
}

**Comment by Grimsbain** [comment]
What was happening when this error showed up because I don't see how it is possible unless the files have been altered in some way.

**Comment by boingylol** [comment]
error happen in dungeons or raid, just did clear update ant took error again. error start from 8.1 patch

**Comment by boingylol** [comment]
and have double error `Message: ...id\modules\oUF_Freebgrid\oUF_Freebgrid_AurasList.lua:705: table index is nil
Time: Sun Dec 16 12:03:54 2018
Count: 1
Stack: ...id\modules\oUF_Freebgrid\oUF_Freebgrid_AurasList.lua:705: table index is nil
...id\modules\oUF_Freebgrid\oUF_Freebgrid_AurasList.lua:705: in main chunk

Locals: _ = "oUF_NeavRaid"
ns = <table> {
 dispelPriority = <table> {
 }
}
oUF = <table> {
 DisableBlizzard = <function> defined @Interface\AddOns\oUF\blizzard.lua:59
 SetActiveStyle = <function> defined @Interface\AddOns\oUF\ouf.lua:411
 EnableFactory = <function> defined @Interface\AddOns\oUF\factory.lua:50
 HCYColorGradient = <function> defined @Interface\AddOns\oUF\colors.lua:221
 ColorGradient = <function> defined @Interface\AddOns\oUF\colors.lua:256
 SpawnHeader = <function> defined @Interface\AddOns\oUF\ouf.lua:610
 RegisterStyle = <function> defined @Interface\AddOns\oUF\ouf.lua:395
 AddElement = <function> defined @Interface\AddOns\oUF\ouf.lua:793
 useHCYColorGradient = false
 RGBToHCY = <function> defined @Interface\AddOns\oUF\colors.lua:150
 Factory = <function> defined @Interface\AddOns\oUF\factory.lua:34
 RGBColorGradient = <function> defined @Interface\AddOns\oUF\colors.lua:128
 SpawnNamePlates = <function> defined @Interface\AddOns\oUF\ouf.lua:697
 Tags = <table> {
 }
 colors = <table> {
 }
 HCYtoRGB = <function> defined @Interface\AddOns\oUF\colors.lua:176
 headers = <table> {
 }
 DisableFactory = <function> defined @Interface\AddOns\oUF\factory.lua:59
 objects = <table> {
 }
 RunFactoryQueue = <function> defined @Interface\AddOns\oUF\factory.lua:69
 RegisterInitCallback = <function> defined @Interface\AddOns\oUF\ouf.lua:366
 RegisterMetaFunction = <function> defined @Interface\AddOns\oUF\ouf.lua:377
 HandleUnit = <function> defined @Interface\AddOns\oUF\units.lua:8
 version = "devel"
 IterateStyles = <function> defined @Interface\AddOns\oUF\ouf.lua:429
 Spawn = <function> defined @Interface\AddOns\oUF\ouf.lua:669
}
spellcache = <table> {
 89421 = <table> {
 }
 256897 = <table> {
 }
 274262 = <table> {
 }
 179864 = <table> {
 }
 250255 = <table> {
 }
 156934 = <table> {
 }
 264556 = <table> {
 }
 118038 = <table> {
 }
 185806 = <table> {
 }
 262513 = <table> {
 }
 268007 = <table> {
 }
 197943 = <table> {
 }
 242017 = <table> {
 }
 186063 = <table> {
 }
 259711 = <table> {
 }
 267626 = <table> {
 }
 183828 = <table> {
 }
 1022 = <table> {
 }
 156107 = <table> {
 }
 115804 = <table> {
 }
 155277 = <table> {
 }
 215128 = <table> {
 }
 247641 = <table> {
 }
 255434 = <table> {
 }
 189260 = <table> {
 }
 161411 = <table> {
 }
 162497 = <table> {
 }
 61336 = <table> {
 }
 179999 = <table> {
 }
 232249 = <table> {
 }
 257544 = <table> {
 }
 181597 = <table> {
 }
 272874 = <table> {
 }
 31850 = <table> {
 }
 204018 = <table> {
 }
 234295 = <table> {
 }
 246687 = <table> {
 }
 265212 = <table> {
 }
 155921 = <table> {
 }
 244899 = <table> {
 }
 266107 = <table> {
 }
 258313 = <table> {
 }
 236596 = <table> {
 }
 160521 = <table> {
 }
 260741 = <table> {
 }
 243431 = <table> {
 }
 179620 = <table> {
 }
 22812 = <table> {
 }
 266238 = <table> {
 }
 244071 = <table> {
 }
 271222 = <table> {
 }
 108271 = <table> {
 }
 155030 = <table> {
 }
 186265 = <table> {
 }
 240559 = <table> {
 }
 5246 = <table> {
 }
 163590 = <table> {
 }
 263943 = <table> {
 }
 157139 = <table> {
 }
 262794 = <table> {
 }
 156309 = <table> {
 }
 162186 = <table> {
 }
 180199 = <table> {
 }
 231363 = <table> {
 }
 156310 = <table> {
 }
 257169 = <table> {
 }
 115203 = <table> {
 }
 155225 = <table> {
 }
 233983 = <table> {
 }
 186333 = <table> {
 }
 161358 = <table> {
 }
 27827 = <table> {
 }
 274555 = <table> {
 }
 270084 = <table> {
 }
 156888 = <table> {
 }
 260685 = <table> {
 }
 159188 = <table> {
 }
 272513 = <table> {
 }
 184355 = <table> {
 }
 230920 = <table> {
 }
 267787 = <table> {
 }
 184931 = <table> {
 }
 272388 = <table> {
 }
 181099 = <table> {
 }
 244016 = <table> {
 }
 263958 = <table> {
 }
 165195 = <table> {
 }
 216040 = <table> {
 }
 180526 = `

**Comment by Grimsbain** [comment]
I just pushed out an update hopefully it will fix your problem but I'm not sure why it is happening in the first place. The only thing I can think of is that Blizzard changed or broke something.

**Comment by boingylol** [comment]
now work fine, thanks
