### ISSUE TITLE
Wrong keybinds for numpad keys

### ISSUE THREAD

**Issue by L3n1n** [lithammer/NeavUI#274]
I found this code in nMainbar/modules/FakeBottomRightBar.lua:

```lua
for i = 1, 9 do
	text = gsub(text, _G["KEY_NUMPAD"..i], "Nu"..i)
end
```

"KEY_NUMPAD" is not exists, "NUMPAD" will be correct:

```lua
for i = 1, 9 do
	text = gsub(text, "NUMPAD"..i, i.."N")
end
```

**Comment by Grimsbain** [comment]
KEY_NUMPAD is a global string and matches the text is applied by Blizzard if you set a binding to the numpad.

KEY_NUMPAD0 = "Num Pad 0";
KEY_NUMPAD1 = "Num Pad 1";
KEY_NUMPAD2 = "Num Pad 2";
KEY_NUMPAD3 = "Num Pad 3";
KEY_NUMPAD4 = "Num Pad 4";
KEY_NUMPAD5 = "Num Pad 5";
KEY_NUMPAD6 = "Num Pad 6";
KEY_NUMPAD7 = "Num Pad 7";
KEY_NUMPAD8 = "Num Pad 8";
KEY_NUMPAD9 = "Num Pad 9";
