### ISSUE TITLE
oUF does not hide Blizzard party frames

### ISSUE THREAD

**Issue by OgulcanCelik** [lithammer/NeavUI#276]
Don't know if it's oUF's problem or another part of the UI, but when I'm in party, Blizzard Party Frames still appear and overlap with oUF Party Frames.

**Comment by Grimsbain** [comment]
oUF handles that. What raid frames do you use? Some add-ons have their own settings and will turn the default frames back on.

**Comment by OgulcanCelik** [comment]
I just tried with minimal setup, only add-ons activated rather than NeavUI set are Immersion, XtoLevel and Bigwigs. However, Blizzard party frames still are there.ß

**Comment by Grimsbain** [comment]
That isn't the default party frame. The defaults have the names above the health not below the power bar. You need to edit the config.lua file in oUF_Neav. Search for party and then set show to false.

**Comment by OgulcanCelik** [comment]
Thank you very much, that fixed it! Also, may I ask another question or do I need to open another issue? Is there any way to move this social button or move the chat border so they don't overlap? Because I can't click it while type overlay is on top of it:
![Image](https://i.imgur.com/NtrUgb1.png)
