### ISSUE TITLE
LUA Error TalkingHeadFrame:SetPoint

### ISSUE THREAD

**Issue by K0uds** [lithammer/NeavUI#277]
Hello,

I have a lot of this type of errors 

Message: Interface\FrameXML\UIParent.lua:2356: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: TalkingHeadFrame:SetPoint.
Time: Sat Jul 20 23:02:11 2019
Count: 34
Stack: Interface\FrameXML\UIParent.lua:2356: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: TalkingHeadFrame:SetPoint.
[C]: in function `SetPoint'
Interface\FrameXML\UIParent.lua:2356: in function <Interface\FrameXML\UIParent.lua:2269>
[C]: in function `securecall'
Interface\FrameXML\UIParent.lua:2974: in function `UIParentManageFramePositions'
Interface\FrameXML\UIParent.lua:2374: in function <Interface\FrameXML\UIParent.lua:2361>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:3170: in function <Interface\FrameXML\UIParent.lua:3168>
[C]: in function `UIParent_ManageFramePositions'
Interface\FrameXML\MainMenuBar.lua:60: in function `SetPositionForStatusBars'
Interface\FrameXML\MainMenuBar.lua:8: in function `OnStatusBarsUpdated'
Interface\FrameXML\StatusTrackingManager.lua:181: in function `LayoutBars'
Interface\FrameXML\StatusTrackingManager.lua:84: in function `UpdateBarsShown'
Interface\FrameXML\StatusTrackingManager.lua:209: in function <Interface\FrameXML\StatusTrackingManager.lua:205>

Locals: (*temporary) = TalkingHeadFrame {
 0 = <userdata>
 OnManagedAlertFrameVisibilityChanged = <function> defined =[C]:-1
 PortraitFrame = <unnamed> {
 }
 NameFrame = <unnamed> {
 }
 SetAlertContainer = <function> defined =[C]:-1
 BackgroundFrame = <unnamed> {
 }
 TextFrame = <unnamed> {
 }
 MainFrame = <unnamed> {
 }
 Show = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 GetAlertContainer = <function> defined =[C]:-1
 alertContainer = AlertFrame {
 }
 OnPostHide = <function> defined =[C]:-1
 ManagesOwnOutroAnimation = <function> defined =[C]:-1
 SetExternallyManagedOutroAnimation = <function> defined =[C]:-1
 isClosing = false
}
(*temporary) = "BOTTOM"
(*temporary) = "UIParent"
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 120

Thanks for you help :)

**Comment by Technojo01** [comment]
I commented out the module in core.lua
`
function nCore_OnEvent(self, event, ...)
    if event == "PLAYER_LOGIN" then
        SetCVar("ScreenshotQuality", 10)
    elseif event == "ADDON_LOADED" then
        local name = ...
        if name == "nCore" then
            nCore:SetDefaultOptions()
            nCore:AltBuy()
            nCore:ArchaeologyHelper()
            nCore:AutoGreed()
            nCore:AutoQuest()
            nCore:Dressroom()
            nCore:Durability()
            nCore:ErrorFilter()
            nCore:Fonts()
            nCore:MapCoords()
            --nCore:MoveTalkingHeads()
            nCore:QuestTracker()
            nCore:ObjectiveTracker()
            nCore:Skins()
            nCore:SpellID()
            nCore:VignetteAlert()
        end
    end
end
`

**Comment by Grimsbain** [comment]
Should be fixed with 7de640cab0b53ee848b35132eea069fd83205b8d.
