### ISSUE TITLE
whats the meaning of the number under the below arrow？

### ISSUE THREAD

**Issue by moshouchajian** [lithammer/NeavUI#287]
whats the meaning of the number under the below arrow？

**Comment by lithammer** [comment]
What number and what arrow?

**Comment by moshouchajian** [comment]
this





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lithammer/NeavUI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 下午3:35
收件人:&nbsp;"lithammer/NeavUI"<NeavUI@noreply.github.com&gt;;
抄送:&nbsp;"金牌电影制作人假的"<320597068@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lithammer/NeavUI] whats the meaning of the number under the below arrow？ (#287)





 
What number and what arrow?

**Comment by moshouchajian** [comment]
the mana bar     u can see the picture under the link

>[https://user.qzone.qq.com/320597068/photo/V54W916D3a1Vlv3Hctt12lngGA1GWMmV/](url)

**Comment by lithammer** [comment]
That link isn't working very well for me. You can attach images directly to comments here on GitHub, just drag-and-drop an image into the textfield like this:

![](https://user-images.githubusercontent.com/499192/57450172-1a955f80-725e-11e9-9fed-267179bdab15.gif)

**Comment by moshouchajian** [comment]
![QQ图片20201016180316](https://user-images.githubusercontent.com/31367184/96248716-93195780-0fde-11eb-8ddd-3952ae716eca.png)

**Comment by lithammer** [comment]
Now I see 🙂 That's the so called "[MP5](https://wowwiki.fandom.com/wiki/MP5)", i.e. the amount of mana regenerated every 5s during combat. It was more important in past expansions.

If you don't like it you can disable it by setting `showCombatRegen` to `false` in `nPower/config.lua`  like this:


```diff
diff --git a/Interface/AddOns/nPower/config.lua b/Interface/AddOns/nPower/config.lua
index 43b99cc..923df11 100644
--- a/Interface/AddOns/nPower/config.lua
+++ b/Interface/AddOns/nPower/config.lua
@@ -6,7 +6,7 @@ nPower.Config = {
     sizeWidth = 200,
     scale = 1.0,
 
-    showCombatRegen = true,
+    showCombatRegen = false,
 
     activeAlpha = 1,
     inactiveAlpha = 0.3,
```

I should probably remove it since it's mostly a relic of the past.

**Comment by moshouchajian** [comment]
thank u ，it works well。

**Comment by moshouchajian** [comment]
I found something about the addon npower。I have to reload when i log in to the game then the arrow shows。
![TQV0N2L{ 3 I{%ZRZ`VU%IN](https://user-images.githubusercontent.com/31367184/96324577-14133600-1055-11eb-9484-37e42d86cfef.png)
![KF7UE`F(2CM~9}MB~4YJFZ5](https://user-images.githubusercontent.com/31367184/96324584-170e2680-1055-11eb-8c06-514ea3df2c92.png)
