### ISSUE TITLE
I found something about the addon npower。I have to reload when i log in to the game then the arrow shows。

### ISSUE THREAD

**Issue by moshouchajian** [lithammer/NeavUI#289]
I found something about the addon npower。I have to reload when i log in to the game then the arrow shows。
![1](https://user-images.githubusercontent.com/31367184/96324623-5472b400-1055-11eb-952e-89f7139ec4e1.png)
![2](https://user-images.githubusercontent.com/31367184/96324627-58063b00-1055-11eb-8200-b428d9dac97a.png)

_Originally posted by @moshouchajian in https://github.com/lithammer/NeavUI/issue_comments/710712403_

**Comment by strickland** [comment]
I was about to post about this, I did not see the arroews and I thought someone changed them, I'm used to them, let me reload to see if it shows! 👍

**Comment by strickland** [comment]
yes upon reloading the arrows show now!, good, hope it gets fixed.

**Comment by strickland** [comment]
i'd like to ask, what is that number 320 at the bottom of the arrow? if anyone knows check SS.

https://imgur.com/a/FOR1IHP

**Comment by lithammer** [comment]
> i'd like to ask, what is that number 320 at the bottom of the arrow? if anyone knows check SS.

See my comment here: https://github.com/lithammer/NeavUI/issues/287#issuecomment-709969637, but the tl;dr is that it's a relic of the past called [MP5](https://wowwiki.fandom.com/wiki/MP5).

**Comment by moshouchajian** [comment]
I love npower，I tried the latest version，but the arrow still needs to be reloaded to display。

**Comment by moshouchajian** [comment]
> > i'd like to ask, what is that number 320 at the bottom of the arrow? if anyone knows check SS.
> 
> See my comment here: [#287 (comment)](https://github.com/lithammer/NeavUI/issues/287#issuecomment-709969637), but the tl;dr is that it's a relic of the past called [MP5](https://wowwiki.fandom.com/wiki/MP5).

I love npower，I tried the latest version，but the arrow still needs to be reloaded to display。

**Comment by moshouchajian** [comment]
I love npower，I tried the latest version，but the arrow still needs to be reloaded to display。

**Comment by lithammer** [comment]
> I love npower，I tried the latest version，but the arrow still needs to be reloaded to display。

Yeah I haven't been able to figure out why that happens. Guess reloading and logging in triggers different events, or in a different order somehow.

**Comment by lithammer** [comment]
Since this isn't critical (just annoying) and there's a workaround I made a release but will continue to investigate.

**Comment by moshouchajian** [comment]
> Since this isn't critical (just annoying) and there's a workaround I made a release but will continue to investigate.

When you upload the new version, I want to experience it. I don't know how to play the game without npower，It's very important to me。

**Comment by strickland** [comment]
I've got a simple WA that mimic exactly how Npower looks and does, ill put it up in wago soon if people are interested.

**Comment by lithammer** [comment]
This should hopefully be fixed by 190e64fd5a62e7f718b322cf86162787f5af8300, please test! If it solves the problem I will upload a new release to WoWI with the latest fixes.
