### ISSUE TITLE
nBuff bug

### ISSUE THREAD

**Issue by Haagen-Dazs** [lithammer/NeavUI#292]
Using master branch:

1x [ADDON_ACTION_BLOCKED] AddOn 'nBuff' tried to call the protected function 'ArenaEnemyFrames:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\UIParent.lua"]:3373: in function `UIParentManageFramePositions'
[string "@FrameXML\UIParent.lua"]:2615: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3411: in function <FrameXML\UIParent.lua:3409>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetBelowMinimapFrame.lua"]:5: in function `layoutFunc'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:473: in function `UpdateWidgetLayout'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:449: in function `ProcessAllWidgets'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:23: in function <...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:21>

**Comment by lithammer** [comment]
When does this happen?

**Comment by Haagen-Dazs** [comment]
> When does this happen?

After joining group during horseman dungeon.

**Comment by lithammer** [comment]
I didn't get this when I did Horseman today. In fact, nBuff isn't even using `ArenaEnemyFrames` anywhere. I wonder if it's a problem when using a specific combination of addons?

**Comment by Haagen-Dazs** [comment]
> 
> 
> I didn't get this when I did Horseman today. In fact, nBuff isn't even using `ArenaEnemyFrames` anywhere. I wonder if it's a problem when using a specific combination of addons?

I disabled all other addons except NeavUI and buggrabber/bugsack, could not reproduce this bug anymore.
Here is the list of all my addons:
BankStack
BigDebuffs
BigWigs
BlockChinese
BugSack
Clique
Details
GTFO
HandyNotes
Leatrix_Plus
LiteBag
LittleWigs
Postal
Prat-3.0

**Comment by lithammer** [comment]
Hmm it seems like maybe BigDebuffs might be a culprit:

- https://github.com/jordonwow/bigdebuffs/issues/90
- https://github.com/jordonwow/bigdebuffs/issues/96

Try to disable _just_ BigDebuffs and see if the solves the problem?

**Comment by Haagen-Dazs** [comment]
> 
> 
> Hmm it seems like maybe BigDebuffs might be a culprit:
> 
>     * [jordonwow/bigdebuffs#90](https://github.com/jordonwow/bigdebuffs/issues/90)
> 
>     * [jordonwow/bigdebuffs#96](https://github.com/jordonwow/bigdebuffs/issues/96)
> 
> 
> Try to disable _just_ BigDebuffs and see if the solves the problem?

Yes, can confirm that it is indeed BigDebuffs that is causing the error.
Tested with BigDebuffs enabled only - got error
Tested all other addons enabled and BigDebuffs disabled - no error.

**Comment by lithammer** [comment]
Unfortunately since there isn't much I can do about it, I'm gonna close this.
