### ISSUE TITLE
nTooltip Double Backgrounds 

### ISSUE THREAD

**Issue by twin2** [lithammer/NeavUI#293]
Hi!
lovely to see this being updated.

This is minor but i report it anyway.

The tooltip is showing 2 layers of backgrounds.

Left is what is in currently, but if i set:
`self.Background:SetColorTexture(0.0, 0.0, 0.0, 0)`
You get the result on the right. 
Also the border from the background below is showing. it is not in my tooltip because i have edited the .blp file.

![image](https://user-images.githubusercontent.com/328699/96451470-ea563c80-1217-11eb-97d1-c2ee73511267.png)

Thanks

/nin

**Comment by lithammer** [comment]
I just pushed a fix (1798623), can you double check if that solves the problem?

**Comment by twin2** [comment]
Still there, let me know if there is anything i can do to help test it.

**Comment by lithammer** [comment]
So I pushed another attempt at fixing this (see b7e9c486ae198e07951f4dfdbfe22f90e0dc478a), please try again 😅

**Comment by twin2** [comment]
Can confirm this works, thank for the swift fix :)

**Comment by lithammer** [comment]
Excellent! I'm glad it worked 🙂
