### ISSUE TITLE
 nPower\core.lua:13: attempt to perform arithmetic on local 'start' (a nil value)

### ISSUE THREAD

**Issue by Haagen-Dazs** [lithammer/NeavUI#294]
Master branch:

60x nPower\core.lua:13: attempt to perform arithmetic on local 'start' (a nil value)
[string "@nPower\core.lua"]:13: in function <nPower\core.lua:11>
[string "@nPower\core.lua"]:130: in function <nPower\core.lua:115>

Locals:
num = 1
start = nil
duration = nil
runeReady = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 8917.432000
(*temporary) = 8917.432000
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'start' (a nil value)"

**Comment by lithammer** [comment]
I'm not really able to reproduce this on my Death Knight. What spec and talent build are you using? Or can you provide a reliable way of triggering this?

**Comment by Haagen-Dazs** [comment]
> 
> 
> I'm not really able to reproduce this on my Death Knight. What level are you and what spec and talent build are you using? Or can you provide a reliable way of triggering this?

Blood DK level 48 with talents: first,first,second,first,second,third (in that order, no last row because still not max level).

**Comment by lithammer** [comment]
I've released 9.0.1 for Shadowlands since I couldn't reproduce it yet so it's hard to fix. I wonder if some addon is causing issues similar to https://github.com/lithammer/NeavUI/issues/292? The error is very weird as well since it indicates that the first rune doesn't exist or something... 🤔

**Comment by lithammer** [comment]
Can you be a bit more specific about when it happens? Is it in combat? Is it in a dungeon or raid? Or PvP?

**Comment by Haagen-Dazs** [comment]
> 
> 
> I've released 9.0.1 for Shadowlands since I couldn't reproduce it yet so it's hard to fix. I wonder if some addon is causing issues similar to #292? The error is very weird as well since it indicates that the first rune doesn't exist or something... 🤔



> 
> 
> Can you be a bit more specific about when it happens? Is it in combat? Is it in a dungeon or raid? Or PvP?
> 
> Also try disabling other addons to see if it still happens.

I was able to reproduce with only NeavUI and Buggrabber/Bugsack enabled after joining Horseman dungeon as a tank, all other addons were disabled.

**Comment by moshouchajian** [comment]
I also have this problem, occasionally when I get on a mount.

AddOns\nPower\core.lua:13: attempt to perform arithmetic on local 'start' (a nil value)
Count: 5

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\nPower\core.lua"]:13: in function <AddOns\nPower\core.lua:11>
[string "@AddOns\nPower\core.lua"]:131: in function <AddOns\nPower\core.lua:116>

**Comment by moshouchajian** [comment]
This error occurs when I transmit

**Comment by lithammer** [comment]
I pushed a commit that should hopefully fix this (see 454da6286b51d9706a7eb4f762e52a127013710b).
