### ISSUE TITLE
Dressing Room naked fix

### ISSUE THREAD

**Issue by Hoodwingk** [lithammer/NeavUI#295]
the naked function in the dressing room no longer works and returns an error.
a fix is to change;
nCore>modules>dressroom.lua Line8 DressUpmodel:Undress() to DressUpFrame.ModelScene:GetPlayerActor():Undress() and then it seems to work fine again.

credit https://us.forums.blizzard.com/en/wow/t/undress-macro-paperdoll-help/459477

**Comment by lithammer** [comment]
I verified the fix and it seems to do the trick. Many thanks for reporting _and_ providing a solution ⭐
