### ISSUE TITLE
nMinimap: Fix for Garrison button

### ISSUE THREAD

**Issue by L3n1n** [lithammer/NeavUI#302]
I found bug with Garrison button. This code isn't working outside hooksecurefunc()

https://github.com/lithammer/NeavUI/blob/bd89bcae34bd5fc03d87cf9eac89f33bcdf53898/Interface/AddOns/nMinimap/core.lua#L55-L57

You need to place this code into hooksecurefunc() and it will be like this:

```lua
hooksecurefunc("GarrisonLandingPageMinimapButton_UpdateIcon", function(self)
	GarrisonLandingPageMinimapButton:SetSize(36, 36)
	GarrisonLandingPageMinimapButton:ClearAllPoints()
	GarrisonLandingPageMinimapButton:SetPoint("BOTTOMLEFT", Minimap, 0, 0)
	
	if C_Garrison.GetLandingPageGarrisonType() == Enum.GarrisonType.Type_8_0 then
		GarrisonLandingPageMinimapButton:SetScale(.70)
	else
		GarrisonLandingPageMinimapButton:SetScale(1)
	end
end)
```

**Comment by lithammer** [comment]
Many thanks! I didn't even notice it myself. Or I thought something looked off but...
