### ISSUE TITLE
nMainbar not showing keybinds

### ISSUE THREAD

**Issue by Haagen-Dazs** [lithammer/NeavUI#303]
nMainbar not showing keybinds or macro text after latest release.

**Comment by Technojo01** [comment]
Works for me... stupid question, did you change the relevant flags in the nMainbar config?

>         showKeybinds = true,
>         showMacroNames = true,

**Comment by Haagen-Dazs** [comment]
> 
> 
> Works for me... stupid question, did you change the relevant flags in the nMainbar config?
> 
> > ```
> >     showKeybinds = true,
> >     showMacroNames = true,
> > ```

Yeah that solves, didn't notice defaults were changed in latest release.
