### ISSUE TITLE
nCore DBM skin: attempt to call method 'SetBackdropColor' (a nil value)

### ISSUE THREAD

**Issue by boecherbrandt** [lithammer/NeavUI#306]
When DBM tries to create bars, I get this error (both when running demo mode and during playing):

Message: Interface\AddOns\nCore\modules\skins.lua:69: attempt to call method 'SetBackdropColor' (a nil value)
Time: Tue Dec 15 17:06:25 2020
Count: 3
Stack: Interface\AddOns\nCore\modules\skins.lua:69: attempt to call method 'SetBackdropColor' (a nil value)
[string "@Interface\AddOns\nCore\modules\skins.lua"]:69: in function <Interface\AddOns\nCore\modules\skins.lua:43>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10943: in function `Start'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:7451: in function `DemoMode'
[string "@Interface\AddOns\DBM-GUI\modules\options\general\Core_GUI.lua"]:58: in function <...\AddOns\DBM-GUI\modules\options\general\Core_GUI.lua:57>

Locals: self = <table> {
 options = <table> {
 }
 defaultOptions = <table> {
 }
 secAnchor = <unnamed> {
 }
 announceHook = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7484
 smallBars = <table> {
 }
 mainAnchor = <unnamed> {
 }
 bars = <table> {
 }
 hugeBars = <table> {
 }
 numBars = 7
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
  = true
}
(for control) = <table> {
 Cancel = <function> defined @Interface\AddOns\DBM-StatusBarTimers\DBT.lua:830
 totalTime = 25
 lastUpdate = 20173.572000
 dummy = true
 dead = true
 small = true
 id = "dummy6"
 owner = <table> {
 }
 colorType = 2
 timer = 25
 frame = DBT_Bar_6 {
 }
 ApplyStyle = <function> defined @Interface\AddOns\DBM-GUI\modules\options\timers\ColorbyType.lua:124
}
bar = <table> {
 Cancel = <function> defined @Interface\AddOns\DBM-StatusBarTimers\DBT.lua:830
 totalTime = 25
 lastUpdate = 20173.572000
 dummy = true
 dead = true
 small = true
 id = "dummy6"
 owner = <table> {
 }
 colorType = 2
 timer = 25
 frame = DBT_Bar_6 {
 }
 ApplyStyle = <function> defined @Interface\AddOns\DBM-GUI\modules\options\timers\ColorbyType.lua:124
}
frame = DBT_Bar_6 {
 0 = <userdata>
 obj = <table> {
 }
}
tbar = DBT_Bar_6Bar {
 0 = <userdata>
 beautyBorder = <table> {
 }
 beautyShadow = <table> {
 }
}
spark = DBT_Bar_6BarSpark {
 0 = <userdata>
}
icon1 = DBT_Bar_6BarIcon1 {
 0 = <userdata>
}
icon2 = DBT_Bar_6BarIcon2 {
 0 = <userdata>
}
name = DBT_Bar_6BarName {
 0 = <userdata>
}
timer = DBT_Bar_6BarTimer {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = DBT_Bar_6Bar {
 0 = <userdata>
 beautyBorder = <table> {
 }
 beautyShadow = <table> {
 }
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0.500000
(*temporary) = "attempt to call method 'SetBackdropColor' (a nil value)"

**Comment by jsimpson** [comment]
The fix for this is to have `tbar` inherit from `BackdropTemplateMixin`, e.g., `Mixin(tbar, BackdropTemplateMixin)`:

```lua
  if IsAddOnLoaded("DBM-Core") then
      hooksecurefunc(DBT, "CreateBar", function(self)
          for bar in self:GetBarIterator() do
              local frame = bar.frame
              local tbar = _G[frame:GetName().."Bar"]
              local spark = _G[frame:GetName().."BarSpark"]
              --local texture = _G[frame:GetName().."BarTexture"]
              local icon1 = _G[frame:GetName().."BarIcon1"]
              local icon2 = _G[frame:GetName().."BarIcon2"]
              local name = _G[frame:GetName().."BarName"]
              local timer = _G[frame:GetName().."BarTimer"]

              spark:SetTexture(nil)

              timer:ClearAllPoints()
              timer:SetPoint("RIGHT", tbar, "RIGHT", -4, 0)
              timer:SetFont(STANDARD_TEXT_FONT, 22)
              timer:SetJustifyH("RIGHT")

              name:ClearAllPoints()
              name:SetPoint("LEFT", tbar, 4, 0)
              name:SetPoint("RIGHT", timer, "LEFT", -4, 0)
              name:SetFont(STANDARD_TEXT_FONT, 15)

              Mixin(tbar, BackdropTemplateMixin)
              tbar:CreateBeautyBorder(10)
              tbar:SetBeautyBorderPadding(tbar:GetHeight() + 3, 2, 2, 2, tbar:GetHeight() + 3, 2, 2, 2)
              tbar:SetBackdrop({bgFile = "Interface\\Buttons\\WHITE8x8"})
              tbar:SetBackdropColor(0, 0, 0, 0.5)

              icon1:SetTexCoord(0.07, 0.93, 0.07, 0.93)
              icon1:SetSize(tbar:GetHeight(), tbar:GetHeight() - 1)

              icon2:SetTexCoord(0.07, 0.93, 0.07, 0.93)
              icon2:SetSize(tbar:GetHeight(), tbar:GetHeight() - 1)
          end
      end)
  end
```

**Comment by boecherbrandt** [comment]
Yep, that did it. Thank you!

**Comment by lithammer** [comment]
Fixed by GH-307

**Comment by lithammer** [comment]
I'm using a BigWigs Bossmods, which probably why this has gone unnoticed. I suspect that it's not only the DBM skinning that suffers from this, unfortunately.
