### ISSUE TITLE
Raid hp color and hp deficit 

### ISSUE THREAD

**Issue by groin** [lithammer/NeavUI#63]
Hi, 
First of all i'm sorry if this isn't the right section for this answers. 
I'm searching to change health color from class color to a grey with alpha, maybe this is the right point     

   -- Health bar

```
self.Health = CreateFrame('StatusBar', nil, self)
self.Health:SetStatusBarTexture(config.media.statusbar, 'ARTWORK')
self.Health:SetAllPoints(self)
self.Health:SetOrientation(config.units.raid.horizontalHealthBars and 'HORIZONTAL' or 'VERTICAL')

self.Health.PostUpdate = UpdateHealth
self.Health.frequentUpdates = true

self.Health.colorClass = true
self.Health.colorDisconnected = true
```

Changing 
Self.health.colorClass=false 

But how can i set a color? 
And above all how can i set class color for health deficit? 

Sorry for my English..

**Comment by Grimsbain** [comment]
@renstrom Not sure what they are trying to do and probably not worth doing at this point.
